# Generated by Django 3.2.13 on 2022-05-18 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0026_auto_20220513_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConsultationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=10)),
                ('other_requirements', models.TextField(blank=True, max_length=200)),
                ('other_comments', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormFillingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('courseoverview', models.ForeignKey(default='course-v1:edX+DemoX+Demo_Course', on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
