# Generated by Django 3.2.13 on 2022-05-18 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_auto_20220513_1339'),
        ('HandsOnPractical', '0001_initial'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='FormFillingDates',
    #     ),
    # ]
