# Generated by Django 3.2.13 on 2022-05-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOnPractical', '0003_coursepracticaldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfillingdates',
            name='courseoverview',
            field=models.ForeignKey(default='course-v1:edX+DemoX+Demo_Course', on_delete=django.db.models.deletion.CASCADE, to='HandsOnPractical.coursepracticaldate'),
        ),
    ]
