# Generated by Django 3.2.13 on 2022-05-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOnPractical', '0004_alter_formfillingdate_courseoverview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentconsultationlist',
            name='course_id',
        ),
        migrations.AddField(
            model_name='formfillingdate',
            name='practical_name',
            field=models.CharField(default='Practical', max_length=50),
        ),
        migrations.AddField(
            model_name='studentconsultationlist',
            name='practical_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HandsOnPractical.formfillingdate'),
        ),
    ]
